twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        Commentaire: '@App\Controller\CommentaireProduitsController'
       
       
        
when@test:
    twig:
        strict_variables: true
        
     
